version: "3"

services:
    app:
        container_name: app
        restart: always
        image: 175817389458.dkr.ecr.us-east-1.amazonaws.com/repository:app
        ports:
            - "4000:4000"
        depends_on:
            - mongo

    client:
        container_name: client
        restart: always
        image: 175817389458.dkr.ecr.us-east-1.amazonaws.com/repository:client
        ports:
            - "3007:3000"
        depends_on:
            - app

    mongo:
        container_name: mongo
        restart: always
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
